### ISSUE TITLE
Fix README (i.e. import)

### ISSUE THREAD

**Issue by ldexterldesign** [denyncrawford/deno-livereload#1]
Hi!

I invite you to update your README as the [import section] looks to be incorrect and when I tried to correct the URL even that is [dead]..?

Hope this helps

Sincerely

[dead]: https://deno.land/x/livereload@0.1.0/mod.ts
[import section]: https://github.com/denyncrawford/deno-livereload#import

**Comment by denyncrawford** [comment]
Thank you, done!
