### ISSUE TITLE
deno.land ThirdParty module error

### ISSUE THREAD

**Issue by grantcarthew** [denyncrawford/deno-livereload#3]
Hey,

I was just trying this module out following the instructions from the README.txt.

Firstly, there is a typo in the import statement. It is `deno.land` not `deno.lanx`, secondly, after fixing this typo it did not import:

```bash
error: Import 'https://deno.land/x/livereload@0.1.0/mod.ts' failed: 404 Not Found
```

I'll import from GitHub for now however I thought you should know.

Thanks.

**Comment by denyncrawford** [comment]
Hi @grantcarthew in the [README.md](https://github.com/denyncrawford/deno-livereload) I can see the import url is fine, please [check it out](https://github.com/denyncrawford/deno-livereload#import), I think there's a typo in a previous version, and I can't change it on deno until publishing a new release, so maybe I'll be releasing a patch to fix the typo on deno.land, thanks for your notice.

**Comment by grantcarthew** [comment]
Sorry Deny, I didn't think to look at the repo Readme. The 'x' is fixed and the address includes 'src'. Thanks mate.
